// Translations for the most common descriptive tags in the source data.
// Tags without an entry are shown as recorded (in Latin script).
import type { L10n } from "./grades";

const T = (en: string, ar: string, ckb: string): L10n => ({ en, ar, ckb });

export const TAGS: Record<string, L10n> = {
  "Ansar": T("Ansar", "الأنصار", "ئەنسار"),
  "Client": T("Client (mawla)", "مولى", "مەولا"),
  "Quraish": T("Quraysh", "قريش", "قورەیش"),
  "Female": T("Woman", "امرأة", "ئافرەت"),
  "Khazraj": T("Khazraj", "الخزرج", "خەزرەج"),
  "Aws": T("Aws", "الأوس", "ئەوس"),
  "Uhud": T("Present at Uhud", "شهد أحدًا", "لە ئوحود ئامادە بوو"),
  "Badr": T("Present at Badr", "شهد بدرًا", "لە بەدر ئامادە بوو"),
  "Khandaq": T("Present at the Trench", "شهد الخندق", "لە خەندەق ئامادە بوو"),
  "Khaybar": T("Present at Khaybar", "شهد خيبر", "لە خەیبەر ئامادە بوو"),
  "Ridwan": T("Pledge of Ridwan", "بيعة الرضوان", "بەیعەتی ڕیزوان"),
  "Aqaba 2": T("Second Pledge of 'Aqaba", "بيعة العقبة الثانية", "بەیعەتی دووەمی عەقەبە"),
  "Abyssinia 2": T("Second migration to Abyssinia", "الهجرة الثانية إلى الحبشة", "کۆچی دووەم بۆ حەبەشە"),
  "Emigrant": T("Emigrant (Muhajir)", "مهاجر", "موهاجیر"),
  "Sahaba": T("Companion", "صحابي", "هاوەڵ"),
  "Early Muslim": T("Early Muslim", "من السابقين إلى الإسلام", "لە پێشینەکانی ئیسلام"),
  "Late Muslim": T("Accepted Islam late", "تأخر إسلامه", "درەنگ موسڵمان بوو"),
  "Born Muslim": T("Born into Islam", "وُلد في الإسلام", "لە ئیسلامدا لەدایکبوو"),
  "Child": T("A child in the Prophet's lifetime", "صغير في حياة النبي ﷺ", "منداڵ بوو لە ژیانی پێغەمبەردا ﷺ"),
  "Makhdaram": T("Mukhadram (lived in both eras)", "مخضرم", "موخەزرەم"),
  "Freed Slave": T("Freed slave", "مُعتَق", "ئازادکراو"),
  "Judge": T("Judge", "قاضٍ", "دادوەر"),
  "Imam": T("Imam", "إمام", "ئیمام"),
  "Hafiz": T("Hafiz", "حافظ", "حافز"),
  "Cousin": T("Cousin of the Prophet ﷺ", "ابن عم النبي ﷺ", "ئامۆزای پێغەمبەر ﷺ"),
  "1st Century": T("1st century AH", "القرن الأول", "سەدەی یەکەمی کۆچی"),
  "Non-Quraish": T("Not of Quraysh", "من غير قريش", "ناقورەیشی"),
  "Ally B.Hashim": T("Ally of Banu Hashim", "حليف بني هاشم", "هاوپەیمانی بەنی هاشم"),
  "B.Hashim": T("Banu Hashim", "بنو هاشم", "بەنی هاشم"),
  "B.al-Muttalib": T("Banu al-Muttalib", "بنو المطلب", "بەنی موتەڵیب"),
  "B.Umayya": T("Banu Umayya", "بنو أمية", "بەنی ئومەییە"),
  "B.'Abd Shams": T("Banu 'Abd Shams", "بنو عبد شمس", "بەنی عەبد شەمس"),
  "B.Zuhrah": T("Banu Zuhra", "بنو زهرة", "بەنی زوهرە"),
  "B.Taym": T("Banu Taym", "بنو تيم", "بەنی تەیم"),
  "B.Asad": T("Banu Asad", "بنو أسد", "بەنی ئەسەد"),
  "B.Makhzum": T("Banu Makhzum", "بنو مخزوم", "بەنی مەخزووم"),
  "B.'Adi": T("Banu 'Adi", "بنو عدي", "بەنی عەدی"),
  "B.Jumah": T("Banu Jumah", "بنو جمح", "بەنی جومەح"),
  "B.Sahm": T("Banu Sahm", "بنو سهم", "بەنی سەهم"),
  "B.'Amir": T("Banu 'Amir", "بنو عامر", "بەنی عامیر"),
  "B.Fihr": T("Banu Fihr", "بنو فهر", "بەنی فیهر"),
  "B.Thaqif": T("Thaqif", "ثقيف", "سەقیف"),
  "B.Haritha": T("Banu Haritha", "بنو حارثة", "بەنی حاریسە"),
  "B.Salima": T("Banu Salima", "بنو سلمة", "بەنی سەلیمە"),
  "B.Zurayq": T("Banu Zurayq", "بنو زريق", "بەنی زوڕەیق"),
  "B.Zafar": T("Banu Zafar", "بنو ظفر", "بەنی زەفەر"),
  "B.Jusham B.al-Khazraj": T("Banu Jusham (Khazraj)", "بنو جشم بن الخزرج", "بەنی جوشەم (خەزرەج)"),
  "B.Malik B.al-Najjar": T("Banu Malik ibn al-Najjar", "بنو مالك بن النجار", "بەنی مالیکی کوڕی نەججار"),
  "B.'Amr B.'Auf": T("Banu 'Amr ibn 'Awf", "بنو عمرو بن عوف", "بەنی عەمری کوڕی عەوف"),
  "B.'Abdul Ashhal": T("Banu 'Abd al-Ashhal", "بنو عبد الأشهل", "بەنی عەبدولئەشهەل"),
  "Kufi": T("of Kufa", "كوفي", "کوفی"),
  "al-Kufi": T("of Kufa", "الكوفي", "کوفی"),
  "al-Kufa": T("of Kufa", "الكوفي", "کوفی"),
  "al-Basri": T("of Basra", "البصري", "بەسری"),
  "Basri": T("of Basra", "البصري", "بەسری"),
  "al-Basra": T("of Basra", "البصري", "بەسری"),
  "al-Madni": T("of Madinah", "المدني", "مەدەنی"),
  "al-Medini": T("of Madinah", "المدني", "مەدەنی"),
  "Madni": T("of Madinah", "المدني", "مەدەنی"),
  "al-Medina": T("of Madinah", "المدني", "مەدەنی"),
  "al-Makki": T("of Makkah", "المكي", "مەککی"),
  "Makki": T("of Makkah", "المكي", "مەککی"),
  "Makkah": T("of Makkah", "المكي", "مەککی"),
  "al-Sham": T("of al-Sham", "الشامي", "شامی"),
  "al-Shami": T("of al-Sham", "الشامي", "شامی"),
  "Shami": T("of al-Sham", "الشامي", "شامی"),
  "al-Masri": T("of Egypt", "المصري", "میسری"),
  "Egypt": T("of Egypt", "المصري", "میسری"),
  "al-Damashqi": T("of Damascus", "الدمشقي", "دیمەشقی"),
  "Damascus": T("of Damascus", "الدمشقي", "دیمەشقی"),
  "Baghdad": T("of Baghdad", "البغدادي", "بەغدادی"),
  "al-Baghdadi": T("of Baghdad", "البغدادي", "بەغدادی"),
  "al-Himsi": T("of Hims", "الحمصي", "حومسی"),
  "Hims": T("of Hims", "الحمصي", "حومسی"),
  "al-Wasti": T("of Wasit", "الواسطي", "واسیتی"),
  "Wasit": T("of Wasit", "الواسطي", "واسیتی"),
  "Hijazi": T("of the Hijaz", "الحجازي", "حیجازی"),
  "al-Hijazi": T("of the Hijaz", "الحجازي", "حیجازی"),
  "Yemen": T("of Yemen", "اليمني", "یەمەنی"),
  "al-Yemeni": T("of Yemen", "اليمني", "یەمەنی"),
  "al-Yemami": T("of al-Yamama", "اليمامي", "یەمامی"),
  "al-Raqqi": T("of al-Raqqa", "الرقي", "ڕەققی"),
  "al-Ramli": T("of al-Ramla", "الرملي", "ڕەملی"),
  "al-Musali": T("of Mosul", "الموصلي", "مووسڵی"),
  "al-Nisapuri": T("of Nishapur", "النيسابوري", "نیشاپووری"),
  "Nisapur": T("of Nishapur", "النيسابوري", "نیشاپووری"),
  "Merv": T("of Merv", "المروزي", "مەروەزی"),
  "al-Mervazi": T("of Merv", "المروزي", "مەروەزی"),
  "al-Bulki": T("of Balkh", "البلخي", "بەلخی"),
  "Bulkh": T("of Balkh", "البلخي", "بەلخی"),
  "al-Khurasni": T("of Khurasan", "الخراساني", "خوراسانی"),
  "Khurasan": T("of Khurasan", "الخراساني", "خوراسانی"),
  "al-Asbahani": T("of Isfahan", "الأصبهاني", "ئەسفەهانی"),
  "al-Ray": T("of al-Rayy", "الرازي", "ڕازی"),
  "al-Jazirah": T("of al-Jazira", "الجزري", "جەزەری"),
  "al-Ta'ifi": T("of Ta'if", "الطائفي", "تائیفی"),
  "Kufa": T("of Kufa", "الكوفي", "کوفی"),
  "al-Tamimi": T("al-Tamimi", "التميمي", "تەمیمی"),
  "al-Azdi": T("al-Azdi", "الأزدي", "ئەزدی"),
  "al-Thaqifi": T("al-Thaqafi", "الثقفي", "سەقەفی"),
  "al-Hamdani": T("al-Hamdani", "الهمداني", "هەمدانی"),
  "al-Salmi": T("al-Sulami", "السلمي", "سولەمی"),
  "al-Nakha'i": T("al-Nakha'i", "النخعي", "نەخەعی"),
  "al-Hadrami": T("al-Hadrami", "الحضرمي", "حەزرەمی"),
  "al-Kundi": T("al-Kindi", "الكندي", "کیندی"),
  "al-'Abdi": T("al-'Abdi", "العبدي", "عەبدی"),
  "al-Bajli": T("al-Bajali", "البجلي", "بەجەلی"),
  "al-Fazari": T("al-Fazari", "الفزاري", "فەزاری"),
  "al-Mazni": T("al-Muzani", "المزني", "موزەنی"),
  "al-Khuza'i": T("al-Khuza'i", "الخزاعي", "خوزاعی"),
  "al-Hanfi": T("al-Hanafi", "الحنفي", "حەنەفی (هۆز)"),
  "al-Laithi": T("al-Laythi", "الليثي", "لەیسی"),
  "al-Tai'i": T("al-Ta'i", "الطائي", "تائی"),
  "al-Aslami": T("al-Aslami", "الأسلمي", "ئەسلەمی"),
  "al-Juhni": T("al-Juhani", "الجهني", "جوهەنی"),
  "al-'Ajli": T("al-'Ijli", "العجلي", "عیجلی"),
  "al-'Anbari": T("al-'Anbari", "العنبري", "عەنبەری"),
  "al-Asha'ri": T("al-Ash'ari", "الأشعري", "ئەشعەری"),
  "al-Sa'di": T("al-Sa'di", "السعدي", "سەعدی"),
  "al-Hadhli": T("al-Hudhali", "الهذلي", "هوزەلی"),
  "al-Ghiffari": T("al-Ghifari", "الغفاري", "غیفاری"),
  "al-Kalbi": T("al-Kalbi", "الكلبي", "کەلبی"),
  "al-Asadi": T("al-Asadi", "الأسدي", "ئەسەدی"),
};

export function translateTag(tag: string, locale: "en" | "ar" | "ckb"): { text: string; translated: boolean } {
  const t = TAGS[tag.trim()];
  if (t) return { text: t[locale], translated: true };
  return { text: tag.trim(), translated: locale === "en" };
}
