/**
 * Generates public/geo/basemap.svg (land outlines for the region where the
 * narrators lived, al-Andalus to Transoxiana, equirectangular projection)
 * and lib/geo/basemap.ts (the projection constants the places map uses).
 * Source: Natural Earth 1:110m via world-atlas (public domain).
 * Run: npx tsx scripts/geo/basemap.ts
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import type { Topology, GeometryCollection } from "topojson-specification";

const require = createRequire(import.meta.url);
const topo = require("world-atlas/land-110m.json") as Topology<{ land: GeometryCollection }>;
const land = feature(topo, topo.objects.land) as unknown as { features: { geometry: { type: string; coordinates: number[][][] | number[][][][] } }[] };

const BBOX = { minLon: -12, maxLon: 76, minLat: 8, maxLat: 46 };
const WIDTH = 1000;
const HEIGHT = Math.round((WIDTH * (BBOX.maxLat - BBOX.minLat)) / (BBOX.maxLon - BBOX.minLon));
const px = (lon: number) => ((lon - BBOX.minLon) / (BBOX.maxLon - BBOX.minLon)) * WIDTH;
const py = (lat: number) => ((BBOX.maxLat - lat) / (BBOX.maxLat - BBOX.minLat)) * HEIGHT;

const parts: string[] = [];
const ring = (coords: number[][]) => {
  const inside = coords.some(([lon, lat]) => lon >= BBOX.minLon - 5 && lon <= BBOX.maxLon + 5 && lat >= BBOX.minLat - 5 && lat <= BBOX.maxLat + 5);
  if (!inside || coords.length < 4) return;
  let d = "";
  let last = "";
  coords.forEach(([lon, lat], i) => {
    const p = `${px(lon).toFixed(1)},${py(lat).toFixed(1)}`;
    if (p === last) return;
    d += (i === 0 ? "M" : "L") + p;
    last = p;
  });
  parts.push(d + "Z");
};
for (const f of land.features) {
  const g = f.geometry;
  if (g.type === "Polygon") (g.coordinates as number[][][]).forEach(ring);
  else (g.coordinates as number[][][][]).forEach((poly) => poly.forEach(ring));
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" width="${WIDTH}" height="${HEIGHT}"><path d="${parts.join("")}" fill="#8a7a5c" fill-opacity="0.22" stroke="#8a7a5c" stroke-opacity="0.45" stroke-width="0.8"/></svg>\n`;
fs.mkdirSync(path.join(process.cwd(), "public", "geo"), { recursive: true });
fs.writeFileSync(path.join(process.cwd(), "public", "geo", "basemap.svg"), svg);
const out = `// Generated by scripts/geo/basemap.ts. Projection of public/geo/basemap.svg.
export const BASEMAP = ${JSON.stringify({ ...BBOX, width: WIDTH, height: HEIGHT })} as const;

export function project(lon: number, lat: number): [number, number] {
  return [
    ((lon - BASEMAP.minLon) / (BASEMAP.maxLon - BASEMAP.minLon)) * BASEMAP.width,
    ((BASEMAP.maxLat - lat) / (BASEMAP.maxLat - BASEMAP.minLat)) * BASEMAP.height,
  ];
}
`;
fs.writeFileSync(path.join(process.cwd(), "lib", "geo", "basemap.ts"), out);
console.log(`basemap: ${parts.length} rings, svg ${(svg.length / 1024).toFixed(0)} KB`);
