// Generated by scripts/geo/basemap.ts. Projection of public/geo/basemap.svg.
export const BASEMAP = {"minLon":-12,"maxLon":76,"minLat":8,"maxLat":46,"width":1000,"height":432} as const;

export function project(lon: number, lat: number): [number, number] {
  return [
    ((lon - BASEMAP.minLon) / (BASEMAP.maxLon - BASEMAP.minLon)) * BASEMAP.width,
    ((BASEMAP.maxLat - lat) / (BASEMAP.maxLat - BASEMAP.minLat)) * BASEMAP.height,
  ];
}
